version: '3.5'

services:
  api:
    build:
      context: ./src
      dockerfile: Dockerfile-api
    image: course-api:latest
    container_name: course-api
    restart: always
    ports:
      - 8080:80
    networks:
      - course-net

  consumer:
    build:
      context: ./src
      dockerfile: Dockerfile-consumer
    image: course-consumer:latest
    container_name: course-consumer
    restart: always
    networks:
      - course-net

  message-bus:
    image: rabbitmq:3-management-alpine
    hostname: course-message-bus
    container_name: course-message-bus
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - course-net

networks:
  course-net:
    name: course-net