FROM microsoft/dotnet:2.1-sdk-alpine as build
WORKDIR /src
COPY . .
# Workaround to remove the api application created in the same context of the consumer
RUN rm -rf MyCompany.Api
WORKDIR /src/MyCompany.Consumer
RUN dotnet publish -c Release -o /dist

FROM microsoft/dotnet:2.1-aspnetcore-runtime-alpine as final
WORKDIR /app
COPY --from=build /dist .
EXPOSE 80
ENTRYPOINT [ "dotnet", "MyCompany.Consumer.dll" ]